# Site wide configuration

title: Proyectos de Universidad
locale: es_ES
description: Paginas que contienen todos los trabajos, ejercicios, examenes y practicas que he ido desarrollando a lo largo de estos años mientras cursaba la titulación de Grado en Ingeniería Informática en la facultad de Granada.
logo: site-logo.png
search: true
<<<<<<< HEAD
url: https://elsudano.github.io/Universidad/
=======
url: https://elsudano.github.io
>>>>>>> 7b389384fd9f4972882c28ee2c63db6dac99d6e8

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Carlos de la Torre
  avatar: bio-photo.jpg
  email: cdelatorre@correo.ugr.es
  disqus-shortname:
  twitter: elsudano
  facebook: #username
  github: elsudano
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: soycarlosdelatorre
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
